### ISSUE TITLE
a user can download a zip of the dat in their browser

### ISSUE THREAD

**Issue by okdistribute** [datproject/dat.land-roadmap#31]

**Comment by okdistribute** [comment]
@maxogden said:

'idea for downloading huge files:

since the window.saveAs buffers the entire file into memory, causing large files to crash the tab, a workaround would be to use a service worker to download the file using webrtc/http and then proxy that into a local http download. so to the user it appears as a standard download in their download manager UI, as opposed to now where it buffers into memory with no progress UI provided by the browser and then saves all at once'

**Comment by laurengarcia** [comment]
i like service worker idea^^. am still wondering if the service worker will hit memory limits tho. was thinking about a simple workaround for this yesterday that might help with memory limits. for a different project, i did something similar to this by simply batching the data in increments and writing into a temp file. 

service worker will also depend on https, so i'll add that to dat.land issues.

**Comment by okdistribute** [comment]
it'd be useful if there was a browser-compatible module that accepted a data stream (i.e., `zip-stream`) and proxied it to the browser's download manager UI

dat.haus could handle downloads differently than the browser, but we should be able to use a streams interface for that too i think

**Comment by laurengarcia** [comment]
this might be helpful: 
https://github.com/webrtc/samples/blob/gh-pages/src/content/datachannel/datatransfer/js/main.js#L95

**Comment by okdistribute** [comment]
in progress: https://github.com/datproject/dat.land/tree/download-button

**Comment by okdistribute** [comment]
I started working on this from the client-side, but ran into issues. It would also not work well with very large .zips. Maybe it would be better to implement this on the server-side?
