### ISSUE TITLE
users own dats on web are auto synced to app

### ISSUE THREAD

**Issue by okdistribute** [datproject/dat.land-roadmap#36]

**Comment by okdistribute** [comment]
this requires user accounts, right? #27

**Comment by okdistribute** [comment]
how do you know which ones are 'yours'?

**Comment by laurengarcia** [comment]
oh yeah, sorry, must have mis-categorized this one. had meant to add it to the Beta milestone.

**Comment by okdistribute** [comment]
duplicate of #48
