### ISSUE TITLE
User should see a message when using an incompatible browser.

### ISSUE THREAD

**Issue by okdistribute** [datproject/dat.land-roadmap#45]
Have a message if they aren't using a compatible browser.

I think we should only support the latest version of Chrome for now, until we have more robust testing on other browsers.

**Comment by Kriesse** [comment]
## Mockup:

![dat land_old-browser-warning](https://cloud.githubusercontent.com/assets/53684/17748805/59131ca6-64bb-11e6-9e32-0e44d3cf755b.png)
